package com.stu.it.accountbook.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "INFO".
 */
public class Info implements Serializable{

    private Long id;
    private Integer type;
    private String date;
    private Double money;
    private String remark;
    private Integer tagId;

    public Info() {
    }

    public Info(Long id) {
        this.id = id;
    }

    public Info(Long id, Integer type, String date, Double money, String remark, Integer tagId) {
        this.id = id;
        this.type = type;
        this.date = date;
        this.money = money;
        this.remark = remark;
        this.tagId = tagId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Double getMoney() {
        return money;
    }

    public void setMoney(Double money) {
        this.money = money;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getTagId() {
        return tagId;
    }

    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    @Override
    public String toString() {
        return "Info{" +
                "id=" + id +
                ", type=" + type +
                ", date='" + date + '\'' +
                ", money=" + money +
                ", remark='" + remark + '\'' +
                ", tagId=" + tagId +
                '}';
    }
}
