package com.stu.it.accountbook.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "TAG".
 */
public class Tag implements Serializable{

    private Long id;
    private Integer type;
    private Integer tag;
    private String name;
    private String tag_remark;

    public Tag() {
    }

    public Tag(Long id) {
        this.id = id;
    }

    public Tag(Long id, Integer type, Integer tag, String name, String tag_remark) {
        this.id = id;
        this.type = type;
        this.tag = tag;
        this.name = name;
        this.tag_remark = tag_remark;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getTag() {
        return tag;
    }

    public void setTag(Integer tag) {
        this.tag = tag;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTag_remark() {
        return tag_remark;
    }

    public void setTag_remark(String tag_remark) {
        this.tag_remark = tag_remark;
    }

    @Override
    public String toString() {
        return "Tag{" +
                "id=" + id +
                ", type=" + type +
                ", tag=" + tag +
                ", name='" + name + '\'' +
                ", tag_remark='" + tag_remark + '\'' +
                '}';
    }
}
